# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# feedback_createFeatureclass.py
# Created on: 2014-10-30 09:56:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy


# Local variables:
GDB_Web = "Database Connections\\GDB_Web(Admin).sde"
feedback_csv = "C:\\Users\\stsmith\\Documents\\VTransGit\\vtp3-home\\geoform\\feedback.csv"
Feedback_Title = "Database Connections\\GDB_Web(Admin).sde\\GDB_Web.ARCIMS.GeoFeedback"
Geo_Feedback = "Database Connections\\GDB_Web(Admin).sde\\GDB_Web.ARCIMS.GeoFeedback"
Feedback_Category = "Database Connections\\GDB_Web(Admin).sde\\GDB_Web.ARCIMS.GeoFeedback"
Feedback_Description = "Database Connections\\GDB_Web(Admin).sde\\GDB_Web.ARCIMS.GeoFeedback"
Your_Name = "Database Connections\\GDB_Web(Admin).sde\\GDB_Web.ARCIMS.GeoFeedback"
Your_Email = "Database Connections\\GDB_Web(Admin).sde\\GDB_Web.ARCIMS.GeoFeedback"
Make_Versioned = "Database Connections\\GDB_Web(Admin).sde\\GDB_Web.ARCIMS.GeoFeedback"

# Process: Table To Domain
arcpy.TableToDomain_management(feedback_csv, "CODE", "DESCRIPTION", GDB_Web, "IssueCategory", "Feedback Type", "REPLACE")

# Process: Create Feature Class
arcpy.CreateFeatureclass_management(GDB_Web, "GeoFeedback", "POINT", "", "DISABLED", "DISABLED", "PROJCS['NAD_1983_StatePlane_Vermont_FIPS_4400',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-72.5],PARAMETER['Scale_Factor',0.9999642857142858],PARAMETER['Latitude_Of_Origin',42.5],UNIT['Meter',1.0]];-5123000 -14708800 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "", "0", "0", "0")

# Process: Add Field (2)
arcpy.AddField_management(Geo_Feedback, "FeedbackTitle", "TEXT", "", "", "50", "Feedback Title (Brief Description)", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field
arcpy.AddField_management(Feedback_Title, "FeedbackCategory", "TEXT", "", "", "250", "Feedback Category", "NULLABLE", "NON_REQUIRED", "IssueCategory")

# Process: Add Field (3)
arcpy.AddField_management(Feedback_Category, "FeedbackDescription", "TEXT", "", "", "250", "Description", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(Feedback_Description, "FeedbackName", "TEXT", "", "", "250", "Your Name (optional)", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (5)
arcpy.AddField_management(Your_Name, "FeedbackEmail", "TEXT", "", "", "", "Your Email Address (optional)", "NULLABLE", "NON_REQUIRED", "")

# Process: Register As Versioned
arcpy.RegisterAsVersioned_management(Your_Email, "NO_EDITS_TO_BASE")

# Process: Enable Attachments
arcpy.EnableAttachments_management(Make_Versioned)

